name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: TrueBrain/actions-flake8@v1.4.1

  tests:
    name: Unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install packages
      run: |
        pip install --upgrade pip setuptools wheel
        pip install pytest-cov coveralls -r test-requirements.txt -e .
    - name: Run tests
      env:
        PYTEST_ADDOPTS: -vv --durations=0 --postgresql-host=postgres --postgresql-password=postgres --cov
      run: python setup.py test
    - name: Upload coverage
      run: pytest --flake8
